call run hydra_ sim1-ts
call run hydra_ sim2-ts
call run hydra_ sim3-ts
call run hydra_ sim4-ts
call run hydra_ sim5-ts
call run hydra_ sim6-ts
call run hydra_ sim7-ts
call run hydra_ sim8-ts
call run hydra_ sim9-ts
call run hydra_ sim10-ts
call run hydra_ sim11-ts
call run hydra_ sim12-ts
call run hydra_ sim13-ts
call run hydra_ sim14-ts
call run hydra_ sim15-ts
call run hydra_ sim16-ts
call run hydra_ sim17-ts
call run hydra_ sim18-ts
call run hydra_ sim19-ts
call run hydra_ sim20-ts
call run hydra_ sim21-ts
call run hydra_ sim22-ts
call run hydra_ sim23-ts
call run hydra_ sim24-ts
call run hydra_ sim25-ts
call run hydra_ sim26-ts
call run hydra_ sim27-ts
call run hydra_ sim28-ts
call run hydra_ sim29-ts
call run hydra_ sim30-ts
call run hydra_ sim31-ts
call run hydra_ sim32-ts
call run hydra_ sim33-ts
call run hydra_ sim34-ts
call run hydra_ sim35-ts
call run hydra_ sim36-ts
call run hydra_ sim37-ts
call run hydra_ sim38-ts
call run hydra_ sim39-ts
call run hydra_ sim40-ts
call run hydra_ sim41-ts
call run hydra_ sim42-ts
call run hydra_ sim43-ts
call run hydra_ sim44-ts
call run hydra_ sim45-ts
call run hydra_ sim46-ts
call run hydra_ sim47-ts
call run hydra_ sim48-ts
call run hydra_ sim49-ts
call run hydra_ sim50-ts
call run hydra_ sim51-ts
call run hydra_ sim52-ts
call run hydra_ sim53-ts
call run hydra_ sim54-ts
call run hydra_ sim55-ts
call run hydra_ sim56-ts
call run hydra_ sim57-ts
call run hydra_ sim58-ts
call run hydra_ sim59-ts
call run hydra_ sim60-ts
call run hydra_ sim61-ts
call run hydra_ sim62-ts
call run hydra_ sim63-ts
call run hydra_ sim64-ts
call run hydra_ sim65-ts
call run hydra_ sim66-ts
call run hydra_ sim67-ts
call run hydra_ sim68-ts
call run hydra_ sim69-ts
call run hydra_ sim70-ts
call run hydra_ sim71-ts
call run hydra_ sim72-ts
call run hydra_ sim73-ts
call run hydra_ sim74-ts
call run hydra_ sim75-ts
call run hydra_ sim76-ts
call run hydra_ sim77-ts
call run hydra_ sim78-ts
call run hydra_ sim79-ts
call run hydra_ sim80-ts
call run hydra_ sim81-ts
call run hydra_ sim82-ts
call run hydra_ sim83-ts
call run hydra_ sim84-ts
call run hydra_ sim85-ts
call run hydra_ sim86-ts
call run hydra_ sim87-ts
call run hydra_ sim88-ts
call run hydra_ sim89-ts
call run hydra_ sim90-ts
call run hydra_ sim91-ts
call run hydra_ sim92-ts
call run hydra_ sim93-ts
call run hydra_ sim94-ts
call run hydra_ sim95-ts
call run hydra_ sim96-ts
call run hydra_ sim97-ts
call run hydra_ sim98-ts
call run hydra_ sim99-ts
call run hydra_ sim100-ts
